name: CICD Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build image
        run: docker build -t shreyasladhe/react-test .
      - name: Publish Docker image to DockerHub
        run: docker push shreyasladhe/react-test:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from DockerHub
        run: docker pull shreyasladhe/react-test:latest
      - name: Delete old container
        run: docker rm -f reactContainertest
      - name: Run Docker container
        run: docker run -d -p 3000:80 --name reactContainertest shreyasladhe/react-test:latest